# Generated by Django 4.2.17 on 2025-01-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_professional',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='professional_license',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='professional_verification',
        ),
    ]
