# Generated by Django 4.2.17 on 2025-02-28 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person making contact', max_length=100)),
                ('email', models.EmailField(help_text='Email address for correspondence', max_length=254)),
                ('subject', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('PRODUCT', 'Product Question'), ('ORDER', 'Order Support'), ('TECHNICAL', 'Technical Support'), ('OTHER', 'Other')], default='GENERAL', help_text='Category of the inquiry', max_length=20)),
                ('message', models.TextField(help_text='Detailed message from the user')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', help_text='Current status of the inquiry', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff (not visible to users)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the request was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the request was last modified')),
                ('user', models.ForeignKey(blank=True, help_text='Registered user who submitted the request (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
