"""
Initial migration for the marketing app.

Creates the NewsletterSubscriber model with the following fields:
- id: Auto-incrementing primary key
- email: Unique email field for subscriber identification
- date_subscribed: Timestamp of subscription
- is_active: Boolean flag for subscription status

Also sets up model metadata for admin interface display.

Generated by Django 4.2.17 on 2025-01-09 11:26
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration creating the NewsletterSubscriber model."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
    ]
