# Generated by Django 4.2.17 on 2025-02-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the order (e.g., verification details)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Indicates if payment has been verified through Stripe webhook'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the order', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_verified',
            field=models.BooleanField(default=False, help_text='Indicates if stock levels were verified for all items'),
        ),
    ]
