# Generated by Django 4.2.17 on 2025-02-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
